name: Go Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.21'

      - name: Install golangci-lint
        run: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.57.2

      - name: Install dependencies
        run: go mod tidy

      - name: Lint
        run: golangci-lint run ./...

      - name: Test
        run: go test ./...